### ISSUE TITLE
bleach_cleanser and mustard_bottle missing collision mesh

### ISSUE THREAD

**Issue by TannerGilbert** [CentralLabFacilities/gazebo_ycb#1]
The bleach_cleanser and mustard_bottle objects both reference nontextured.stl for the geometry mesh. The nontextured files where added in f652494308a4e30369a60a1406e0402819746f77 but then removed in 42c98fd7087342e9063c920480e272eb7f379046 without updating the SDF files. This currently leads to the boxes for example being invisible for a robot camera.

**Potential fixes:**
1. Add nontextured.stl for both models to the repository again
2. Use old box geometry that currently exists as comments in both SDF file
3. Use textured.dae mesh (for me the mustard_bottle toppled over when I used the textured.dae for some reason).

**Comment by LeroyR** [comment]
We are not using `gazebo` anymore. But afair gazebo uses the visuals for cameras - do you mean invisible to depth sensors?

Is the main issue for missing collisions not falling through the world?  :sweat_smile: 

Anyway i will generate collision meshes for the two objects.

**Comment by LeroyR** [comment]
Fixed in 064676296d6f463617d79c71c6e5ab571dd0a5bf

**Comment by LeroyR** [comment]
Uh.. we  normally use decimated meshes for other use cases, after thinking about it, they may just be toppling all over. the place.
Just report back in that case :smile:

**Comment by TannerGilbert** [comment]
@LeroyR sorry for the delayed reply. The mustard_bottle is indeed falling over when placed on an even surface. For reference the STL mesh from f652494308a4e30369a60a1406e0402819746f77 worked. Also in general thanks for the quick initial response.
